namespace Domain.Shared;

/// <summary>
/// Creates entity identifiers.
/// </summary>
/// <remarks>
/// Version 7 UUIDs are time-ordered, so inserts append to the end of a B-tree
/// index instead of scattering across it, and rows sort naturally by creation
/// time without a second column. They are generated by the application rather
/// than the database, so no round trip is needed to learn an id.
/// </remarks>
public static class CulinaId
{
    /// <summary>A new time-ordered identifier.</summary>
    public static Guid New() => Guid.CreateVersion7();
}
